services:
  api:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    expose:
      - "8080"
    env_file:
      - .dev.env
    volumes:
      - './:/usr/app:rw'
  db:
    image: mysql
    env_file:
      - .dev.env
    expose:
      - "3306"
    ports:
      - "3306:3306"
    command: --log-bin-trust-function-creators=1
    volumes:
      - "./data:/var/lib/mysql"
