version: "3.5"
services:
  api:
    build: .
    depends_on: 
      - db
    ports:
      - "8080:8080"
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: blueshell
      MYSQL_DATABASE: blueshell
      MYSQL_USER: tim
      MYSQL_PASSWORD: blueshell
    volumes: 
      - "./data:/var/lib/mysql"
