spring:
  datasource:
    url: jdbc:mariadb://db:3306/blueshell?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 300000         # 5 minutes
      max-lifetime: 1800000        # 30 minutes
      connection-timeout: 30000    # 30 seconds
      connection-test-query: "SELECT 1"

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
      hibernate.enable_lazy_load_no_trans: true


  flyway:
    enabled: true
    locations: classpath:db/migration

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mvc:
    dispatch-options-request: true

app:
  url: ${APP_URL}
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000

frontend:
  url: ${FRONTEND_URL}

storage:
  location: ./uploads
