INSERT INTO blueshell.news (id, creator_id, last_editor_id, news_type, title, content, posted_at) VALUES (4, 1, 1, 'news', 'Brace yourselves – Summer is coming', '<div><p>If you haven’t noticed yet with the many BBQ’s being organized throughout the campus, the wonderful weather we are having or  your study demanding your last breath of effort for these final few weeks, the summer holidays are approaching! What does this mean for Blueshell? Well, it means this is your chance to already get a bit of the holiday feeling and relax at a few of our activities (hint: sign-up can happen somewhere here at the site). Moreover, we hope that at the end of this month, we can announce the first candidate board for Blueshell! These will take over the reins after the summer holidays, and all of the members can expect an invite for the official Blueshell GMM (general members meeting).</p>
<p>But let’s not look too far forward, there is still plenty to do. We as a board are still interested in looking to improve the Discord (our main communication channel), and we are glad a few members have offered their help, seeing as the board is not exactly ‘’experienced’’ with this wonderful platform. Moreover, there are still plenty of ideas we would like to take up, so don’t be surprised when you see some brand new idea announcements on the Discord! Moreover, don’t forget Blueshell runs on its members – don’t hesistate to contact us to start organizing something, and when you think about starting up a solo game of LoL or climb the ladder in Hearthstone, ask in the channel if anyone is up for some fun! We wish you all the best in these last few weeks of the year, good luck with your studies, and take (a deserved) break of those same studies to come to our activities. </p>
<p>See you soon!</p>
</div>', '2018-05-10 21:42:51');
INSERT INTO blueshell.news (id, creator_id, last_editor_id, news_type, title, content, posted_at) VALUES (3, 1, 1, 'news', 'Candidate Board & First year of Blueshell', '<div><p>With summer approaching, so does the end of the first year of Blueshell E-sports. As a board, we are very content with the current state of Blueshell, having a healthy memberbase, great potential to grow and most importantly: a lot of fun for everyone interested in gaming. Moreover, where other associations may struggle to find a candidate board, we immeadiately had some members jump at the opportunity, and ended up with five enthusaistic gamers that will carry on (and create) Blueshell’s legacy:</p>
<p><em>Jasper van Harten as Chairman</em></p>
<p><em>Kimberly Evertsz as Secretary</em></p>
<p><em>Mauk Muller as Treasurer</em></p>
<p><em>Antal van Dongen as Commissioner of Internal Affairs</em></p>
<p><em>Maiander Eigenraam as Commissioner of External affairs</em></p>
<p>Don’t worry you won’t see us again till next year! While our (local) activities might not be as regular as normally, the summer holidays are an excellent opportunity to make some new friends! So hop on our Discord, ask around a bit for people to play with and jump into a game with a fellow student you didn’t know before!</p>
<p>We wish you all the best with finishing up your academic year!</p>
</div>', '2018-06-14 06:09:40');
INSERT INTO blueshell.news (id, creator_id, last_editor_id, news_type, title, content, posted_at) VALUES (2, 1, 1, 'news', 'New cooperation El Nino!', '<div><p>Dear Blueshellers,</p>
<p>We are proud to announce that Blueshell has started a new professional cooperation with El Niño, a firm from Enschede specialized in digitization and automation. Different from other large firms, El Niño has a very personal approach, delivering custom solutions to complex IT problems. For us, their support allows us to continue to establish an E-sports and gaming community in Twente.<br>
If you are interested in the firm, or if you would like to come into contact with them, be sure to visit <a href="https://web.archive.org/web/20201028103827/https://www.elnino.tech/">their site</a>! We look forward to a successful year for both Blueshell and El Niño.</p>
<p><a href="https://www.elnino.tech/"></a></p>
</div>', '2018-07-14 06:09:40');
INSERT INTO blueshell.news (id, creator_id, last_editor_id, news_type, title, content, posted_at) VALUES (9, 1, 1, 'news', 'Looking for players for our League of Legends teams!', '<div><p>Are you looking to take your game to the next level? Do you want to represent Blueshell Esports in League of Legends tournaments? Then you came to the right place! If you’re Diamond 4+ this season as well, you can tryout for the BS Primus team that will participate in the Dutch College League for League of Legends!</p>
<p><a href="https://docs.google.com/forms/d/e/1FAIpQLSemOJBVMkUvaTfDlCkrQlMwTeFJ_pmb-YEevGP1xIau397_oA/viewform">Click here to sign up!</a></p>
</div>', '2019-09-08 21:50:06');
INSERT INTO blueshell.news (id, creator_id, last_editor_id, news_type, title, content, posted_at) VALUES (8, 1, 1, 'news', 'Post event feedback: 4th of October LoL Tournament', '<div><p>It’s been two weeks since the League of Legends tournament on 4th of October happened and it’s time to look back and reflect upon it. The event was a big success, with over 80 people signing up and 16 teams in total. This was actually the biggest League tourney we’ve ever had so far in the history of Blueshell and we hope the next ones are gonna be even bigger! We would also like to congratulate again BS Primus for winning the tournament!</p></div>', '2019-10-19 21:48:10');
INSERT INTO blueshell.news (id, creator_id, last_editor_id, news_type, title, content, posted_at) VALUES (7, 1, 1, 'news', 'BS Primus wins 1-0 against Zephyr Nox!', '<div><p>Our League of Legends team, BS Primus, has won another match in the Premier League of Dutch College League against Zephyr Nox! We are currently 2-0 and first in our groups! Lets go boys!</p></div>', '2019-12-16 21:47:37');
INSERT INTO blueshell.news (id, creator_id, last_editor_id, news_type, title, content, posted_at) VALUES (6, 1, 1, 'news', 'Upcoming League of Legends Tournament on the 28th of February', '<div><p>Blueshell Esports is organizing another League of Legends 5v5 tournament on the 28th of February! For this occasion, we are also doing promotion stands in front of Ravelijn and Horst on the 3rd and 4th of February. Come over during the lunch break to say hi to the committee and for some free hot Chocomel! For more info about the tournament, please go to our Events page.</p>
</div>', '2020-02-03 21:45:59');
INSERT INTO blueshell.news (id, creator_id, last_editor_id, news_type, title, content, posted_at) VALUES (5, 1, 1, 'news', 'WIRWAR – LAN party at the FC Twente Stadium!', '<div><div><div>
<div>
	<h5><strong>What is WIRWAR?</strong></h5>
<p>On the 9<sup>th</sup> of October 2020 something special will happen at the FC Twente stadium. This is the moment when the first edition of the <strong>WIRWAR LAN party</strong> will be held. During the Lan party, you can experience competitive gaming, console gaming, retro games, and VR games in a Total Reality room. The event will start at 15:00 and will end in the late evening. This all will create a gaming atmosphere unique for the region of Twente mixing gaming enthusiasts from regional companies and students from the UT and Saxion! Additionally, representatives from the Esportslab of the University of Twente and the Esports Team Twente will also be present.</p>
</div>
</div></div><div><div>
<div>
	<h5><strong></strong><strong>How do I register?</strong></h5>
<p>For more information and registration, follow this <a href="http://wirwar.gg/" target="_blank" rel="noopener noreferrer">link </a>to WIRWAR''s official website. Moreover, for student visitors, there is a discount available when you use the following code in the registration form: <strong>WRWRstudent.</strong></p>
<h5><strong></strong></h5>
</div>
</div></div></div>', '2020-09-19 21:45:15');