insert into committees (id, name, description) values (1, 'MPLS Networking', 'Mandatory fault-tolerant model'),
(2, 'PTP', 'Streamlined composite policy'),
(3, 'Architecture', 'Reactive logistical knowledge user'),
(4, 'Internet Banking', 'Seamless regional hardware'),
(5, 'iGrafx', 'Right-sized modular architecture'),
(6, 'Allergy', 'Reverse-engineered local system engine'),
(7, 'iPod', 'Profit-focused background encoding'),
(8, 'PSD', 'Automated intangible process improvement'),
(9, 'VMware vSphere', 'Total radical time-frame'),
(10, 'Thermodynamics', 'Intuitive contextually-based database'),
(11, 'MPBN', 'Integrated mission-critical protocol'),
(12, 'VLAN', 'Triple-buffered holistic open architecture'),
(13, 'DQL', 'Grass-roots systematic Graphic Interface'),
(14, 'MBAL', 'Multi-tiered asymmetric Graphical User Interface'),
(15, 'IAM', 'Inverse regional service-desk'),
(16, 'FCNSA', 'Function-based intangible portal'),
(17, 'Electronic Payments', 'Realigned needs-based website'),
(18, 'TSCM', 'Face to face interactive productivity'),
(19, 'UCCE', 'Visionary responsive encryption'),
(20, 'European Politics', 'Future-proofed contextually-based definition');
