insert into event_feedback (id, feedback, event_id) values (1, 'Synchronised impactful data-warehouse', 8),
(2, 'Right-sized interactive access', 85),
(3, 'Expanded zero tolerance process improvement', 8),
(4, 'Business-focused impactful intranet', 54),
(5, 'Configurable directional focus group', 92),
(6, 'User-friendly empowering concept', 56),
(7, 'Persistent responsive leverage', 11),
(8, 'Networked mission-critical process improvement', 89),
(9, 'Innovative attitude-oriented service-desk', 71),
(10, 'Synergized multimedia firmware', 88),
(11, 'Adaptive background complexity', 24),
(12, 'Ameliorated non-volatile encryption', 84),
(13, 'Cross-group full-range model', 4),
(14, 'Pre-emptive user-facing methodology', 53),
(15, 'Multi-lateral tertiary help-desk', 75),
(16, 'Seamless tertiary portal', 7),
(17, 'Persevering contextually-based functionalities', 32),
(18, 'Reverse-engineered solution-oriented implementation', 95),
(19, 'Switchable secondary superstructure', 86),
(20, 'Devolved zero defect open architecture', 38),
(21, 'Horizontal bottom-line infrastructure', 19),
(22, 'Cross-platform incremental throughput', 89),
(23, 'Organic bottom-line approach', 40),
(24, 'Intuitive motivating focus group', 7),
(25, 'Cloned didactic matrices', 34),
(26, 'Synergistic next generation task-force', 90),
(27, 'Devolved background archive', 29),
(28, 'De-engineered executive local area network', 29),
(29, 'Synergized modular strategy', 65),
(30, 'Open-source national policy', 86),
(31, 'Networked solution-oriented open architecture', 12),
(32, 'Pre-emptive leading edge utilisation', 16),
(33, 'Quality-focused executive info-mediaries', 94),
(34, 'Upgradable upward-trending capability', 13),
(35, 'Mandatory grid-enabled model', 12),
(36, 'Digitized neutral portal', 91),
(37, 'Fully-configurable 6th generation framework', 33),
(38, 'Re-contextualized asymmetric parallelism', 96),
(39, 'Focused stable local area network', 25),
(40, 'Face to face disintermediate access', 61),
(41, 'Cross-group static process improvement', 13),
(42, 'Face to face human-resource paradigm', 68),
(43, 'Multi-channelled regional matrix', 84),
(44, 'Profit-focused regional task-force', 88),
(45, 'User-friendly cohesive encryption', 97),
(46, 'Phased grid-enabled infrastructure', 13),
(47, 'Innovative context-sensitive leverage', 22),
(48, 'Organic multi-tasking core', 21),
(49, 'Phased 6th generation encoding', 94),
(50, 'Operative national adapter', 51),
(51, 'Ergonomic heuristic time-frame', 82),
(52, 'Intuitive asynchronous strategy', 83),
(53, 'Organized impactful challenge', 48),
(54, 'User-friendly neutral initiative', 46),
(55, 'Face to face scalable database', 43),
(56, 'Secured reciprocal instruction set', 84),
(57, 'Cross-platform exuding definition', 27),
(58, 'Customizable leading edge superstructure', 38),
(59, 'Re-contextualized asynchronous access', 83),
(60, 'Face to face impactful focus group', 93),
(61, 'Synergistic radical open architecture', 9),
(62, 'Face to face object-oriented installation', 82),
(63, 'Digitized demand-driven flexibility', 86),
(64, 'Front-line multi-state matrix', 97),
(65, 'De-engineered full-range circuit', 60),
(66, 'Business-focused stable system engine', 8),
(67, 'Streamlined 5th generation neural-net', 23),
(68, 'Future-proofed motivating process improvement', 87),
(69, 'Open-architected background methodology', 24),
(70, 'Customer-focused asymmetric conglomeration', 59),
(71, 'Operative attitude-oriented strategy', 66),
(72, 'Face to face modular interface', 18),
(73, 'Organized logistical budgetary management', 92),
(74, 'Managed user-facing approach', 49),
(75, 'Persevering zero defect intranet', 12),
(76, 'Cloned uniform architecture', 76),
(77, 'Vision-oriented logistical success', 80),
(78, 'Innovative executive product', 99),
(79, 'Virtual asymmetric parallelism', 68),
(80, 'Decentralized encompassing alliance', 78),
(81, 'Customer-focused dedicated synergy', 85),
(82, 'Inverse systemic attitude', 45),
(83, 'Secured value-added toolset', 70),
(84, 'Mandatory heuristic emulation', 8),
(85, 'Stand-alone system-worthy contingency', 51),
(86, 'Fully-configurable mobile knowledge user', 57),
(87, 'Expanded upward-trending core', 89),
(88, 'Monitored empowering complexity', 84),
(89, 'Quality-focused exuding utilisation', 58),
(90, 'Reactive responsive open system', 14),
(91, 'Networked web-enabled database', 53),
(92, 'Universal bottom-line toolset', 72),
(93, 'Virtual asynchronous circuit', 84),
(94, 'Adaptive mission-critical moratorium', 62),
(95, 'Inverse clear-thinking functionalities', 73),
(96, 'Ameliorated stable Graphical User Interface', 14),
(97, 'Re-engineered multimedia open system', 51),
(98, 'Cross-platform asynchronous methodology', 96),
(99, 'Multi-lateral mobile database', 42),
(100, 'Automated fault-tolerant collaboration', 86);
